In [1]:
import pandas as pd
import phate
import scprep
import scanpy as sc
import numpy as np
from scipy.spatial.distance import pdist, squareform, cdist
# matplotlib settings for Jupyter notebooks only
%matplotlib inline
DATA_PATH = '/gpfs/gibbs/pi/krishnaswamy_smita/xingzhi/sea_ad/data/'

In [2]:
adata = sc.read_h5ad(DATA_PATH + 'SEAAD_MTG_RNAseq_subset_2000cellsperbraak_PREPROCESSED.h5ad')

In [3]:
adata = adata[adata.obs['Class'] == 'Neuronal: GABAergic']

In [4]:
phate_operator = phate.PHATE()
Y_phate = phate_operator.fit_transform(adata[:, adata.var['highly_variable']])

Calculating PHATE...
  Running PHATE on 3785 observations and 3515 variables.
  Calculating graph and diffusion operator...
    Calculating PCA...
    Calculated PCA in 1.21 seconds.
    Calculating KNN search...
    Calculated KNN search in 1.82 seconds.
    Calculating affinities...
    Calculated affinities in 0.13 seconds.
  Calculated graph and diffusion operator in 3.17 seconds.
  Calculating landmark operator...
    Calculating SVD...
    Calculated SVD in 0.22 seconds.
    Calculating KMeans...
    Calculated KMeans in 3.30 seconds.
  Calculated landmark operator in 4.11 seconds.
  Calculating optimal t...
    Automatically selected t = 26
  Calculated optimal t in 3.17 seconds.
  Calculating diffusion potential...
  Calculated diffusion potential in 1.12 seconds.
  Calculating metric MDS...
  Calculated metric MDS in 3.95 seconds.
Calculated PHATE in 15.64 seconds.


In [20]:
pca_loadings = phate_operator.graph.data_nu

In [17]:
pca = phate_operator.graph.data_pca

In [16]:
phate_operator.graph.data_pca.inverse_transform()

<bound method _BasePCA.inverse_transform of PCA(n_components=100, svd_solver='randomized')>

In [10]:
pca_loadings.shape

(3785, 100)

In [11]:
adata

View of AnnData object with n_obs × n_vars = 3785 × 36601
    obs: 'sample_id', 'Neurotypical reference', 'Donor ID', 'Organism', 'Brain Region', 'Sex', 'Gender', 'Age at Death', 'Race (choice=White)', 'Race (choice=Black/ African American)', 'Race (choice=Asian)', 'Race (choice=American Indian/ Alaska Native)', 'Race (choice=Native Hawaiian or Pacific Islander)', 'Race (choice=Unknown or unreported)', 'Race (choice=Other)', 'specify other race', 'Hispanic/Latino', 'Highest level of education', 'Years of education', 'PMI', 'Fresh Brain Weight', 'Brain pH', 'Overall AD neuropathological Change', 'Thal', 'Braak', 'CERAD score', 'Overall CAA Score', 'Highest Lewy Body Disease', 'Total Microinfarcts (not observed grossly)', 'Total microinfarcts in screening sections', 'Atherosclerosis', 'Arteriolosclerosis', 'LATE', 'Cognitive Status', 'Last CASI Score', 'Interval from last CASI in months', 'Last MMSE Score', 'Interval from last MMSE in months', 'Last MOCA Score', 'Interval from last MOCA 

In [49]:
data2 = np.load('../data/sea_ad_gaba_all.npz')

In [50]:
data2['data'] - pca_loadings

array([[-5.32907052e-15, -3.55271368e-15,  5.32907052e-14, ...,
        -7.16302624e-01,  2.46846028e-01,  3.44925750e-02],
       [-5.32907052e-15,  1.76525461e-14, -1.68753900e-14, ...,
         4.88987893e-02, -4.36582926e-01,  1.84811014e-01],
       [-7.10542736e-15,  6.21724894e-15,  3.90798505e-14, ...,
         4.35936911e-01, -8.14882291e-01,  1.34302022e+00],
       ...,
       [ 7.10542736e-15, -1.06581410e-14,  2.62012634e-14, ...,
        -8.60727304e-01,  1.09123092e+00,  7.16036280e-01],
       [ 3.55271368e-15, -1.26565425e-14,  2.66453526e-14, ...,
        -2.55081590e-01, -1.09226923e+00, -4.95581637e-03],
       [ 8.88178420e-16,  1.02140518e-14,  3.28626015e-14, ...,
        -6.75206904e-01, -4.62457025e-02, -5.67578525e-01]])

In [51]:
# it is not very much the same, but we will use it for the moment.

In [53]:
pca.components_

array([[ 0.00060362,  0.00090317, -0.00202548, ...,  0.00343086,
         0.00182051, -0.00508616],
       [ 0.00315327,  0.00051637,  0.00063625, ...,  0.00344764,
         0.00313943,  0.00351479],
       [ 0.00388572,  0.00088412, -0.00040877, ...,  0.00222295,
         0.0013491 ,  0.00484364],
       ...,
       [-0.0047036 , -0.00454297, -0.00303237, ..., -0.02447931,
         0.0242335 , -0.00101614],
       [-0.01848613, -0.00131021, -0.00033535, ...,  0.03178551,
         0.02228669, -0.00370962],
       [-0.00209951, -0.00493077, -0.00015823, ..., -0.0396839 ,
         0.05656155,  0.02836441]])

In [54]:
pca.mean_

array([0.09549589, 0.01828979, 0.1018056 , ..., 1.25732205, 0.57702178,
       1.0928504 ])

In [55]:
np.savez('../data/sea_ad_all_pcs_correct.npz', pca_loadings=pca.components_, data_mean=pca.mean_)