In [1]:
import numpy as np
import graphtools

In [2]:
root_path = "../../synthetic_data4/"
data_names = ["noisy_1_groups_17580_3000_1_0.18_0.5_all","noisy_1_groups_17580_3000_1_0.25_0.5_all","noisy_1_groups_17580_3000_1_0.5_0.5_all","noisy_1_groups_17580_3000_1_0_0.5_all","noisy_1_paths_17580_3000_1_0.18_0.5_all","noisy_1_paths_17580_3000_1_0.25_0.5_all","noisy_1_paths_17580_3000_1_0.5_0.5_all","noisy_1_paths_17580_3000_1_0_0.5_all","noisy_2_groups_17580_3000_1_0.18_0.5_all","noisy_2_groups_17580_3000_1_0.25_0.5_all","noisy_2_groups_17580_3000_1_0.5_0.5_all","noisy_2_groups_17580_3000_1_0_0.5_all","noisy_2_paths_17580_3000_1_0.18_0.5_all","noisy_2_paths_17580_3000_1_0.25_0.5_all","noisy_2_paths_17580_3000_1_0.5_0.5_all","noisy_2_paths_17580_3000_1_0_0.5_all","noisy_3_groups_17580_3000_1_0.18_0.5_all","noisy_3_groups_17580_3000_1_0.25_0.5_all","noisy_3_groups_17580_3000_1_0.5_0.5_all","noisy_3_groups_17580_3000_1_0_0.5_all","noisy_3_paths_17580_3000_1_0.18_0.5_all","noisy_3_paths_17580_3000_1_0.25_0.5_all","noisy_3_paths_17580_3000_1_0.5_0.5_all","noisy_3_paths_17580_3000_1_0_0.5_all","noisy_4_groups_17580_3000_1_0.18_0.5_all","noisy_4_groups_17580_3000_1_0.25_0.5_all","noisy_4_groups_17580_3000_1_0.5_0.5_all","noisy_4_groups_17580_3000_1_0_0.5_all","noisy_4_paths_17580_3000_1_0.18_0.5_all","noisy_4_paths_17580_3000_1_0.25_0.5_all","noisy_4_paths_17580_3000_1_0.5_0.5_all","noisy_4_paths_17580_3000_1_0_0.5_all","noisy_5_groups_17580_3000_1_0.18_0.5_all","noisy_5_groups_17580_3000_1_0.25_0.5_all","noisy_5_groups_17580_3000_1_0.5_0.5_all","noisy_5_groups_17580_3000_1_0_0.5_all","noisy_5_paths_17580_3000_1_0.18_0.5_all","noisy_5_paths_17580_3000_1_0.25_0.5_all","noisy_5_paths_17580_3000_1_0.5_0.5_all","noisy_5_paths_17580_3000_1_0_0.5_all"]

In [6]:
name = data_names[0]
splited_name = name.split("_")
true_name = f"true_{splited_name[1]}_{splited_name[2]}_{splited_name[3]}_{splited_name[4]}_{splited_name[5]}_all"

In [7]:
true_name

'true_1_groups_17580_3000_1_all'

In [37]:
name = data_names[0]
data = np.load(f"{root_path}/{name}.npz")

In [16]:
data.files

['data', 'colors', 'dist', 'dist_all', 'phate', 'is_train']

In [17]:
data['data'].shape

(3000, 100)

In [18]:
G1 = graphtools.Graph(data['data'], knn=5, decay=None)
D1 = G1.shortest_path(distance='data')

In [19]:
name = 'true_1_groups_17580_3000_1_all'
data_noiseless = np.load(f"{root_path}/{name}.npz")

In [20]:
G2 = graphtools.Graph(data_noiseless['data'], knn=5, decay=None)
D2 = G2.shortest_path(distance='data')

In [21]:
D1

array([[ 0.        , 70.93130174, 70.09154941, ..., 72.27446526,
        71.63497206, 90.23384747],
       [70.93130174,  0.        , 70.23494122, ..., 54.86952757,
        89.87325483, 79.69582837],
       [70.09154941, 70.23494122,  0.        , ..., 86.33140903,
        55.70443353, 55.11269255],
       ...,
       [72.27446526, 54.86952757, 86.33140903, ...,  0.        ,
        80.58464573, 96.53957518],
       [71.63497206, 89.87325483, 55.70443353, ..., 80.58464573,
         0.        , 73.91113659],
       [90.23384747, 79.69582837, 55.11269255, ..., 96.53957518,
        73.91113659,  0.        ]])

In [22]:
D2

array([[  0.        ,  34.85567322,          inf, ...,  36.08930515,
         97.23501991,          inf],
       [ 34.85567322,   0.        ,          inf, ...,  30.02172546,
        100.62463705,          inf],
       [         inf,          inf,   0.        , ...,          inf,
                 inf,  34.87795371],
       ...,
       [ 36.08930515,  30.02172546,          inf, ...,   0.        ,
        110.63428877,          inf],
       [ 97.23501991, 100.62463705,          inf, ..., 110.63428877,
          0.        ,          inf],
       [         inf,          inf,  34.87795371, ...,          inf,
                 inf,   0.        ]])

In [23]:
def sample_non_inf_pairs(distance_matrix, num_pairs=20, seed=None):
    if seed is not None:
        np.random.seed(seed)
    
    # Identify non-infinity entries in the distance matrix
    non_inf_indices = np.argwhere(np.isfinite(distance_matrix))
    
    # Convert to list of tuples
    non_inf_pairs = [tuple(pair) for pair in non_inf_indices if pair[0] != pair[1]]  # Exclude diagonal elements
    
    # Check if there are enough pairs to sample from
    if len(non_inf_pairs) < num_pairs:
        raise ValueError("Not enough non-infinity pairs to sample from.")
    
    # Randomly sample 20 pairs using numpy
    sampled_pairs_indices = np.random.choice(len(non_inf_pairs), size=num_pairs, replace=False)
    sampled_pairs = [non_inf_pairs[i] for i in sampled_pairs_indices]
    
    return sampled_pairs



In [25]:
pairs = sample_non_inf_pairs(D2, seed=432)

In [26]:
pairs

[(261, 1822),
 (2282, 320),
 (1149, 2019),
 (73, 790),
 (345, 2153),
 (165, 2893),
 (1705, 984),
 (2485, 1675),
 (1642, 2555),
 (2852, 920),
 (2313, 2455),
 (2536, 1961),
 (1051, 2558),
 (376, 1063),
 (2939, 2235),
 (1046, 1173),
 (1764, 845),
 (1980, 668),
 (2685, 851),
 (736, 1474)]

In [31]:
d2s = [D2[p[0], p[1]] for p in pairs]

In [32]:
d1s = [D1[p[0], p[1]] for p in pairs]

In [34]:
np.corrcoef(d2s, d1s)[0,1]

0.8320695486534964

In [36]:
((np.array(d2s) - np.array(d1s))**2).mean()

365.8693675924137

In [8]:
true_dat = np.load(f"{root_path}/gt/{true_name}.npz")

In [13]:
start_idx, end_idx = true_dat['pairs'].T

In [14]:
start_idx

array([ 261, 2282, 1149,   73,  345,  165, 1705, 2485, 1642, 2852, 2313,
       2536, 1051,  376, 2939, 1046, 1764, 1980, 2685,  736])

In [15]:
end_idx

array([1822,  320, 2019,  790, 2153, 2893,  984, 1675, 2555,  920, 2455,
       1961, 2558, 1063, 2235, 1173,  845,  668,  851, 1474])